#theme: jekyll-theme-minimal
remote_theme: jianhuanliu/modernist
title: Welcome to my first Website!
description: Near-surface Seismic Imaging Tools
author:
  name: Jianhuan Liu
  email: zeng.j.liu.2017@gmail.com
